spring:
  application:
    name: time-tracker
  docker:
    compose:
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://192.168.0.54:5432/mydatabase
    username: myuser
    password: secret
#  jpa:
#    hibernate:
#      ddl-auto: update

#vaadin:
#  launch-browser: true

logging:
  level:
    co:
      ptm:
        timetracker:
          api:
            service: DEBUG
          ui: DEBUG
server:
  servlet:
    context-path: /api/v1